// <auto-generated />
namespace GOT.Prolegis.Model.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class EntityTypeDefaultData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EntityTypeDefaultData));
        
        string IMigrationMetadata.Id
        {
            get { return "201209161431292_EntityTypeDefaultData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
