// <auto-generated />
namespace GOT.Prolegis.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class tblUserTableAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tblUserTableAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201211181457594_tblUserTableAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
